### ISSUE TITLE
Ubuntu 18.04 - Script exits after "Loading open gapps"

### ISSUE THREAD

**Issue by mbe14** [geeks-r-us/anbox-playstore-installer#48] opened 2020-04-11 18:29 UTC
I suspect the script breaks somewhere after the line "Loading open gapps"
This is the full output:

mihai@lxle01:~$ ./install-playstore.sh
/var/snap/anbox/common/rootfs-overlay
/home/mihai/anbox-work
Extracting anbox android image
Parallel unsquashfs: Using 4 processors
1836 inodes (8401 blocks) to write

[=============================================================\] 8401/8401 100%

created 1659 files
created 280 directories
created 177 symlinks
created 0 devices
created 0 fifos
Loading open gapps from https://sourceforge.net/projects/opengapps/files/x86_64/20200407/open_gapps-x86_64-7.1-pico-20200407.zip
mihai@lxle01:~$ 

EDIT: link to open_gapps is broken:
`The "/x86_64/20200407/ope...1-pico-20200407.zip" file could not be found or is not available. Please select another file.`

**Comment by mbe14** [comment] 2020-04-11 18:50
Workaround:
Go to https://sourceforge.net/projects/opengapps/files/x86_64/ and note the last modified parent folder.
Edit install-playstore.sh at lines 102 and 103 which are using the `OPENGAPPS_RELEASEDATE` variable. Set variable value to the name of the last modified parent folder (ex. 20200403)
Please close this issue.
Thank you!

**Comment by geeks-r-us** [comment] 2020-04-20 13:24
Duplicate of #47

**Closed by geeks-r-us** 2020-04-20 13:24 UTC
